# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'StackExchange' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StackExchange
  pod 'Alamofire', '~> 4.0'

  target 'StackExchangeTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire', '~> 4.0'
  end

  target 'StackExchangeUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire', '~> 4.0'
  end

end
